version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: markus
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Crecenia_chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U markus"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chatbot_net

  adminer:
    image: adminer:latest
    container_name: chatbot_adminer
    restart: always
    depends_on:
      postgres:
        condition: service_healthy   
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8081:8080"
    networks:
      - chatbot_net

networks:
  chatbot_net:
    driver: bridge

volumes:
  postgres_data:
